---
- name: "PostgresSQL | install packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
    - postgresql-server
  notify: enable postgres

- name: "PostgresSQL | copy init file"

- name: "PostgresSQL | run db initialization"

- name: "PostgresSQL | create user and schema"